# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('암컷', '암컷'), ('수컷', '수컷')], max_length=2),
        ),
    ]
