# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180629_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='find_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
